import type { Metadata } from "next";
import "./globals.css";
import Header from "./header/header"
import {Arimo} from "next/font/google"

const arimo = Arimo({subsets:['latin']})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${arimo.className} antialiased`}
      >
        <div className="w-full z-10">
          <Header/>
        </div>
        {children}
      </body>
    </html>
  );
}
