import type { Metadata } from "next";
import "./globals.css";
import Header from "./header/header"
import {Urbanist} from "next/font/google"

const urbanist = Urbanist({subsets:['latin']})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${urbanist.className} antialiased h-screen flex flex-col`}
      >
          <Header/>
          {children}
    </body>
    </html>
  );
}
